#print("Hello World!")
#print("Hello again")
#print("I like typing this.")
#print("This is fun.")
#print('Yay! Priting.')
#print("I'd much rather you 'not'.")
#print('I "said" do not touch this.')
#print('Another line.')
print('Only one line')
